# Generated by Django 5.0.4 on 2024-05-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=650),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='courses/images/'),
        ),
    ]
