# Generated by Django 5.0.4 on 2024-05-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_hours_course_instructor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_hours',
            field=models.FloatField(),
        ),
    ]
