# Generated by Django 5.0.4 on 2024-05-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrolling'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolling',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrolling',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
