# Generated by Django 5.0.4 on 2024-05-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_enrolling_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolling',
            name='course_id',
        ),
        migrations.AddField(
            model_name='enrolling',
            name='course',
            field=models.ForeignKey(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
