# Generated by Django 5.0.4 on 2024-04-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('national_identity', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('<django.db.models.fields.CharField>.pdf', models.FileField(upload_to='certificates/', verbose_name='Certificate')),
            ],
        ),
    ]
