# Generated by Django 5.0.4 on 2024-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_delete_cetdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='<django.db.models.fields.CharField>.pdf',
            new_name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.pdf',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
