# Generated by Django 5.0.4 on 2024-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_rename__django_db_models_fields_charfield_pdf_certificate__django_db_models_fields_charfield___djang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.pdf',
            field=models.FileField(upload_to='media/certificates/', verbose_name='Certificate'),
        ),
    ]
