# Generated by Django 5.0.4 on 2024-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_alter_certificate__django_db_models_fields_charfield___django_db_models_fields_charfield_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.pdf',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
