# Generated by Django 5.0.4 on 2024-04-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_remove_certificate__django_db_models_fields_charfield___django_db_models_fields_charfield_pdf_and_mo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate',
        ),
        migrations.AddField(
            model_name='certificate',
            name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.pdf',
            field=models.FileField(default=1, upload_to='media/certificates/', verbose_name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.pdf'),
            preserve_default=False,
        ),
    ]
