# Generated by Django 5.0.4 on 2024-04-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_alter_certificate__django_db_models_fields_charfield___django_db_models_fields_charfield_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.pdf',
            new_name='certificate',
        ),
    ]
