# Generated by Django 5.0.4 on 2024-05-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_alter_certificate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cimg',
            field=models.ImageField(default=1, upload_to='certificates/images/', verbose_name='Certificate Image'),
            preserve_default=False,
        ),
    ]
